name: WebUI-FTP
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WebUI-FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.WEBUI_FTP_SERVER }}
          user: ${{ secrets.WEBUI_FTP_USERNAME }}
          password: ${{ secrets.WEBUI_FTP_PASSWORD }}
          local_dir: "./server"
          remote_dir: "./public_html"
          delete: "true"
          ftp_ssl_allow: "false"
          max_retries: "3"
